owner: kishikawakatsumi
repo: status.applelocalization.com

sites:
  - name: applelocalization.com
    url: https://applelocalization.com/healthz

status-website:
  cname: status.applelocalization.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Apple Localization Terms Glossary Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/20 * * * *"
